const page=document.getElementById("page"), modalBg=document.getElementById("modalBg"), modal=document.getElementById("modal");
const state={incidents:[
{id:1,type:"Minor collision",location:"Market Circle",time:"8 min ago",severity:"High",status:"Open"},
{id:2,type:"Road obstruction",location:"Lake Junction",time:"19 min ago",severity:"Medium",status:"Open"},
{id:3,type:"Camera offline",location:"North Gate",time:"31 min ago",severity:"Low",status:"Open"},
{id:4,type:"Slow traffic",location:"Central Avenue",time:"42 min ago",severity:"Medium",status:"Open"}],
junctions:[
["Central Square","J-001","92%","48 km/h","08","Optimal"],["Lake Junction","J-004","61%","31 km/h","24","Busy"],["Tech Park","J-007","84%","43 km/h","12","Optimal"],["Market Circle","J-009","32%","18 km/h","51","Congested"],["North Gate","J-011","77%","39 km/h","14","Optimal"],["Airport Road","J-014","68%","34 km/h","19","Busy"]]};
const names={overview:"Network Overview",junctions:"Junction Performance",incidents:"Incident Center",routes:"Route Intelligence",cameras:"Camera Network",analytics:"Traffic Analytics",reports:"Reports & Insights",settings:"System Settings"};

function toast(title,detail="Action completed successfully."){const t=document.getElementById("toast");t.innerHTML=`<b>✓ ${title}</b><small>${detail}</small>`;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2600)}
function setPage(name){document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));const n=document.querySelector(`[data-page="${name}"]`);if(n)n.classList.add("active");document.getElementById("breadcrumb").textContent=names[name];page.innerHTML=views[name]();if(innerWidth<760)document.getElementById("sidebar").classList.remove("mobile");}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>setPage(n.dataset.page));

function header(title,sub,buttons=""){return `<div class="page-title"><div style="display:flex;justify-content:space-between;align-items:end"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${buttons}</div></div></div>`}
function status(s){return `<span class="status ${s==="Optimal"?"good":s==="Busy"?"warn":"bad"}">${s}</span>`}

const views={
overview:()=>`<div class="hero"><div><div class="eyebrow">TUESDAY · OCT 06, 2026 · LIVE</div><h1>Good morning, Hanuma <span>✦</span></h1><p class="muted">Your entire traffic network at a glance.</p></div><div class="actions"><button class="btn secondary" onclick="refresh()">↻ Refresh</button><button class="btn primary" onclick="exportCSV()">↓ Export report</button></div></div>
<div class="kpis">${kpi("Network flow","78.4","%","↑ 8.6%","vs yesterday",["28","43","35","56","50","70","63","82","72","92"])}${kpi("Average speed","42.8","km/h","↑ 4.2%","vs yesterday",["65","54","70","48","73","78","68","88","76","94"])}${kpi("Active incidents","04","","↑ 2","in the last hour",["20","40","70","90","15"])}${kpi("Average delay","06:42","min","↓ 12.8%","improvement",["85","70","55","60","45","35","28"] )}</div>
<div class="grid2"><section class="card panel">${chartPanel()}</section><section class="card panel">${mapPanel()}</section></div>
<div class="grid-bottom"><section class="card panel">${junctionTable()}</section><section class="card panel">${incidentList()}</section></div>`,

junctions:()=>header("Junction Performance","Monitor, search and manage every priority intersection.",`<button class="btn secondary" onclick="refresh()">↻ Sync</button><button class="btn primary" onclick="addJunction()">+ Add junction</button>`)
+`<div class="toolbar"><input class="search" id="junctionSearch" placeholder="⌕ Search junction or ID..." oninput="filterJunctions()"><select class="select" id="junctionFilter" onchange="filterJunctions()"><option>All statuses</option><option>Optimal</option><option>Busy</option><option>Congested</option></select></div><section class="card data-card" id="junctionTable">${junctionTable(true)}</section>`,

incidents:()=>header("Incident Center","Detect, assign, review and resolve network incidents.",`<button class="btn primary" onclick="addIncident()">+ Report incident</button>`)
+`<div class="toolbar"><input class="search" id="incidentSearch" placeholder="⌕ Search incidents..." oninput="renderIncidents()"><select class="select" onchange="renderIncidents()" id="incidentFilter"><option>All</option><option>Open</option><option>Resolved</option></select></div><section class="card data-card" id="incidentTable">${incidentTable()}</section>`,

routes:()=>header("Route Intelligence","Compare route health, travel time and congestion.",`<button class="btn primary" onclick="optimizeRoute()">⚡ Optimize routes</button>`)
+`<div class="route-grid">${["Central → Airport","North Gate → Tech Park","Market → Riverside","Airport → Downtown","Lake → Central","Tech Park → Ring Road"].map((x,i)=>`<div class="card route-card"><div class="panel-head"><div><h2>${x}</h2><p>Route ${String(i+1).padStart(2,"0")} · ${i%2?"7.4":"9.2"} km</p></div>${status(i%3===0?"Optimal":i%3===1?"Busy":"Congested")}</div><div class="route-line"><i style="width:${35+i*9}%"></i></div><div class="route-meta"><span>Travel <b>${12+i*3} min</b></span><span>Delay <b>${i+2} min</b></span></div><button class="small-btn" style="margin-top:13px" onclick="routeDetails('${x}')">View route details →</button></div>`).join("")}</div>`,

cameras:()=>header("Camera Network","48 cameras monitored across 12 traffic zones.",`<button class="btn secondary" onclick="scanCameras()">↻ Scan network</button>`)
+`<div class="toolbar"><input class="search" placeholder="⌕ Search camera..." oninput="filterCards(this,'camera-grid')"><select class="select"><option>All locations</option><option>Central</option><option>North</option><option>Airport</option></select></div><div class="camera-grid">${["Central Square CAM-01","Lake Junction CAM-04","Tech Park CAM-07","Market Circle CAM-09","North Gate CAM-11","Airport Road CAM-14"].map((x,i)=>`<div class="card camera"><div class="camera-feed"><span class="camera-live">${i===2?"ONLINE":"LIVE"}</span><div class="cars"></div></div><div class="camera-info"><strong>${x}</strong><p>${i===2?"Online · 1080p · 30 FPS":"Online · 1080p · 24 FPS"}</p><button class="small-btn" onclick="openCamera('${x}')">Open live feed</button><button class="small-btn" onclick="cameraSettings('${x}')">⚙</button></div></div>`).join("")}</div>`,

analytics:()=>header("Traffic Analytics","Explore network performance and historical trends.",`<button class="btn primary" onclick="exportCSV()">↓ Export analytics</button>`)
+`<div class="analytics-grid">${metric("Vehicles / hour","12,842","↑ 14.2%"),metric("Peak congestion","08:45 AM","Morning peak"),metric("Network efficiency","86.7%","↑ 6.8%")}</div><div class="grid2" style="margin-top:14px"><section class="card panel"><div class="panel-head"><div><h2>Hourly vehicle volume</h2><p>Today · all junctions</p></div></div><div class="bar-chart">${[35,42,55,39,48,68,81,96,88,72,64,58,70,76,84,73,61,48,42,35].map(x=>`<i style="height:${x}%"></i>`).join("")}</div></section><section class="card panel"><div class="panel-head"><div><h2>Traffic distribution</h2><p>Vehicle classification</p></div></div><div style="padding:25px;text-align:center"><div style="width:150px;height:150px;border-radius:50%;margin:auto;background:conic-gradient(#6259e8 0 48%,#29acd7 48% 73%,#efa23b 73% 89%,#e85f6d 89%);display:grid;place-items:center"><div style="width:92px;height:92px;border-radius:50%;background:var(--card);display:grid;place-items:center"><b style="font:700 20px Space Grotesk">100%</b></div></div><p class="muted" style="margin-top:15px">Cars 48% · Bikes 25% · Bus 16% · Trucks 11%</p></div></section></div>`,

reports:()=>header("Reports & Insights","Generate downloadable operational reports.",`<button class="btn primary" onclick="exportCSV()">↓ Download CSV</button>`)
+`<div class="route-grid">${["Daily traffic summary","Incident performance","Junction efficiency","Camera uptime","Route comparison","Monthly network report"].map((x,i)=>`<div class="card route-card"><div style="font-size:28px;color:#6259e8">▤</div><h2 style="margin-top:12px">${x}</h2><p class="muted">Updated ${i+1} hour${i?"s":""} ago · ${120+i*34} records</p><button class="btn primary" style="margin-top:12px;width:100%" onclick="generateReport('${x}')">Generate report</button></div>`).join("")}</div>`,

settings:()=>header("System Settings","Configure dashboard, alerts and network preferences.")
+`<div class="settings-grid">${setting("Live data refresh","Automatically refresh traffic readings",true)}${setting("Incident notifications","Notify when a high-severity incident appears",true)}${setting("Sound alerts","Play an alert for critical congestion",false)}${setting("Compact tables","Show more rows with less spacing",false)}${setting("Auto-center map","Keep the map focused on active incidents",true)}${setting("Privacy mode","Hide operator information from shared screens",false)}</div><section class="card panel" style="margin-top:14px"><h2>System information</h2><p class="muted" style="margin-top:7px">FlowSight v2.0 · 48 cameras · 12 junctions · API status: Operational</p><button class="btn secondary" style="margin-top:12px" onclick="toast('System test passed','All connected services are responding normally.')">Run system test</button></section>`
};

function kpi(a,b,c,d,e,bars){return `<article class="card kpi"><div class="kpi-title">${a}</div><div class="kpi-value">${b} <small>${c}</small></div><div class="${d.includes('↓')?'up':'up'}">${d} <span class="kpi-foot">${e}</span></div><div class="mini-bars">${bars.map(h=>`<i style="height:${h}%"></i>`).join("")}</div></article>`}
function metric(a,b,c){return `<div class="card metric"><span>${a}</span><strong>${b}</strong><span style="color:#21ad7c">${c}</span></div>`}
function chartPanel(){return `<div class="panel-head"><div><h2>Traffic volume</h2><p>Vehicles detected across the network</p></div><div class="segment">${["24H","7D","30D"].map((x,i)=>`<button class="${i===0?"active":""}" onclick="chartRange(this,'${x}')">${x}</button>`).join("")}</div></div><div style="display:flex;justify-content:space-between;margin-top:18px"><span class="legend"><i></i> Vehicles</span><span class="legend">Peak <b id="peak">12.8K</b></span></div><div class="chart"><svg viewBox="0 0 800 240" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#6259e8" stop-opacity=".25"/><stop offset="1" stop-color="#6259e8" stop-opacity="0"/></linearGradient></defs><g class="grid"><line x1="0" y1="35" x2="800" y2="35"/><line x1="0" y1="95" x2="800" y2="95"/><line x1="0" y1="155" x2="800" y2="155"/><line x1="0" y1="215" x2="800" y2="215"/></g><path class="area" d="M0 205 C40 190 55 180 95 190 S155 145 195 165 S245 110 290 140 S350 75 395 112 S450 125 495 92 S545 120 585 70 S650 62 690 82 S750 35 800 55 L800 215 L0 215Z"/><path class="line" d="M0 205 C40 190 55 180 95 190 S155 145 195 165 S245 110 290 140 S350 75 395 112 S450 125 495 92 S545 120 585 70 S650 62 690 82 S750 35 800 55"/></svg></div><div class="chart-labels"><span>12 AM</span><span>4 AM</span><span>8 AM</span><span>12 PM</span><span>4 PM</span><span>8 PM</span><span>12 AM</span></div>`}
function mapPanel(){return `<div class="panel-head"><div><h2>Live network map</h2><p>12 junctions · 48 cameras online</p></div><button class="small-btn" onclick="mapRefresh()">⌾ Center</button></div><div class="map"><div class="map-grid"></div><div class="road a"></div><div class="road b"></div><div class="road c"></div><div class="road d"></div>${[['p1','Central Square','92%','good'],['p2','Lake Junction','61%','warn'],['p3','Tech Park','84%','good'],['p4','Market Circle','32%','bad'],['p5','North Gate','77%','good']].map(x=>`<button class="pin ${x[3]} ${x[0]}" onclick="pin('${x[1]}','${x[2]}')"></button>`).join("")}<div class="map-tools"><button onclick="zoom(1)">+</button><button onclick="zoom(-1)">−</button><button onclick="mapRefresh()">⌾</button></div><div class="map-legend"><span><i class="green"></i> Smooth</span><span><i class="orange"></i> Busy</span><span><i class="red"></i> Congested</span></div></div>`}
function junctionTable(full=false){return `<div class="panel-head"><div><h2>Junction performance</h2><p>${full?"All priority intersections":"Live status of priority intersections"}</p></div>${!full?`<button class="small-btn" onclick="setPage('junctions')">View all →</button>`:""}</div><div style="overflow:auto;margin-top:12px"><table><thead><tr><th>Junction</th><th>Flow</th><th>Speed</th><th>Queue</th><th>Status</th>${full?"<th>Action</th>":""}</tr></thead><tbody>${state.junctions.map((r,i)=>`<tr class="junction-row" data-text="${r.join(" ").toLowerCase()}"><td><b>${r[0]}</b><br><small style="color:#a3aab6">${r[1]}</small></td><td><div class="progress"><i style="width:${r[2]}"></i></div></td><td>${r[3]}</td><td>${r[4]}</td><td>${status(r[5])}</td>${full?`<td><button class="small-btn" onclick="junctionDetails('${r[0]}')">Manage</button></td>`:""}</tr>`).join("")}</tbody></table></div>`}
function incidentList(){return `<div class="panel-head"><div><h2>Recent incidents</h2><p>Last 60 minutes</p></div><button class="small-btn" onclick="setPage('incidents')">View all →</button></div><div class="list">${state.incidents.slice(0,3).map(x=>`<div class="list-row"><div class="list-icon">!</div><div><strong>${x.type}</strong><p>${x.location} · ${x.time}</p></div><span class="tag ${x.severity.toLowerCase()}">${x.severity}</span></div>`).join("")}</div>`}
function incidentTable(){return `<div style="overflow:auto"><table><thead><tr><th>Incident</th><th>Location</th><th>Time</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.incidents.map(x=>`<tr><td><b>${x.type}</b></td><td>${x.location}</td><td>${x.time}</td><td><span class="tag ${x.severity.toLowerCase()}">${x.severity}</span></td><td>${x.status}</td><td>${x.status==="Open"?`<button class="small-btn" onclick="resolveIncident(${x.id})">Resolve</button>`:`<button class="small-btn" onclick="reopenIncident(${x.id})">Reopen</button>`}</td></tr>`).join("")}</tbody></table></div>`}
function setting(name,desc,on){return `<div class="card setting"><div><b>${name}</b><p>${desc}</p></div><button class="toggle ${on?"on":""}" onclick="this.classList.toggle('on');toast('${name} updated','Preference saved.')"><i></i></button></div>`}

function refresh(){toast("Data refreshed","All traffic readings are current.");}
function chartRange(btn,r){btn.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.getElementById("peak").textContent={24:"12.8K",7:"15.4K",30:"18.2K"}[r==="24H"?24:r==="7D"?7:30];toast(`${r} range selected`,"Chart data updated.")}
function pin(n,f){openModal(`<button class="close" onclick="closeModal()">×</button><h2>${n}</h2><p>Live junction status</p><div class="metric card" style="margin-top:15px"><span>Current traffic flow</span><strong>${f}</strong><span>Average speed: 42 km/h</span></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Close</button><button class="btn primary" onclick="junctionDetails('${n}')">Manage junction</button></div>`)}
function mapRefresh(){toast("Map centered","Network center and active junctions are visible.")}
function zoom(x){toast(x>0?"Map zoomed in":"Map zoomed out","Map view updated.")}
function filterJunctions(){const q=(document.getElementById("junctionSearch").value||"").toLowerCase(),f=document.getElementById("junctionFilter").value;document.querySelectorAll(".junction-row").forEach(r=>{const ok=r.dataset.text.includes(q)&&(f==="All statuses"||r.dataset.text.includes(f.toLowerCase()));r.style.display=ok?"":"none"})}
function filterCards(input,cls){const q=input.value.toLowerCase();document.querySelectorAll("."+cls+" > *").forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q)?"":"none")}
function renderIncidents(){const q=(document.getElementById("incidentSearch").value||"").toLowerCase(),f=document.getElementById("incidentFilter").value;document.getElementById("incidentTable").innerHTML=incidentTable();document.querySelectorAll("#incidentTable tbody tr").forEach(r=>{const text=r.innerText.toLowerCase();r.style.display=text.includes(q)&&(f==="All"||text.includes(f.toLowerCase()))?"":"none"})}
function resolveIncident(id){const x=state.incidents.find(i=>i.id===id);x.status="Resolved";renderIncidents();document.getElementById("incidentCount").textContent=state.incidents.filter(i=>i.status==="Open").length;toast("Incident resolved",`${x.type} at ${x.location} was closed.`)}
function reopenIncident(id){state.incidents.find(i=>i.id===id).status="Open";renderIncidents();toast("Incident reopened")}
function addIncident(){openModal(`<button class="close" onclick="closeModal()">×</button><h2>Report new incident</h2><p>Add an event to the live incident center.</p><div class="form"><label>Incident type<input id="newType" placeholder="e.g. Vehicle breakdown"></label><label>Location<input id="newLocation" placeholder="Junction or road"></label><label>Severity<select id="newSeverity"><option>Low</option><option>Medium</option><option>High</option></select></label></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveIncident()">Create incident</button></div>`)}
function saveIncident(){const type=document.getElementById("newType").value||"Traffic incident",location=document.getElementById("newLocation").value||"Unknown location",severity=document.getElementById("newSeverity").value;state.incidents.unshift({id:Date.now(),type,location,time:"just now",severity,status:"Open"});document.getElementById("incidentCount").textContent=state.incidents.length;closeModal();toast("Incident created","New incident is now being monitored.")}
function addJunction(){openModal(`<button class="close" onclick="closeModal()">×</button><h2>Add junction</h2><p>Register a new monitored intersection.</p><div class="form"><label>Junction name<input id="jName" placeholder="e.g. Stadium Road"></label><label>Junction ID<input id="jId" placeholder="J-020"></label></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveJunction()">Add junction</button></div>`)}
function saveJunction(){const n=document.getElementById("jName").value||"New Junction",id=document.getElementById("jId").value||"J-020";state.junctions.push([n,id,"70%","36 km/h","15","Busy"]);closeModal();setPage("junctions");toast("Junction added",`${n} is now in the monitoring list.`)}
function junctionDetails(n){openModal(`<button class="close" onclick="closeModal()">×</button><h2>${n}</h2><p>Junction control panel</p><div class="settings-grid" style="margin-top:14px"><div class="card metric"><span>Signal cycle</span><strong>82 sec</strong><span>Adaptive mode</span></div><div class="card metric"><span>Queue length</span><strong>18</strong><span>vehicles</span></div></div><div class="modal-actions"><button class="btn secondary" onclick="toast('Signal optimized','Adaptive signal timing updated.')">Optimize signals</button><button class="btn primary" onclick="closeModal()">Done</button></div>`)}
function routeDetails(n){openModal(`<button class="close" onclick="closeModal()">×</button><h2>${n}</h2><p>Live route intelligence</p><div class="form"><div class="card metric"><span>Estimated travel time</span><strong>14 min</strong><span>Current conditions</span></div><div class="card metric"><span>Alternative route</span><strong>11 min</strong><span>Save 3 minutes</span></div></div><div class="modal-actions"><button class="btn secondary" onclick="closeModal()">Close</button><button class="btn primary" onclick="toast('Route selected','Alternative route has been applied.');closeModal()">Use faster route</button></div>`)}
function optimizeRoute(){toast("Routes optimized","Fastest available paths are now highlighted.")}
function openCamera(n){openModal(`<button class="close" onclick="closeModal()">×</button><h2>${n}</h2><p>Live camera feed · 1080p</p><div class="camera-feed" style="height:240px;margin-top:15px"><span class="camera-live">LIVE</span><div class="cars"></div></div><div class="modal-actions"><button class="btn secondary" onclick="toast('Snapshot captured','Image saved to the session.')">Take snapshot</button><button class="btn primary" onclick="closeModal()">Close feed</button></div>`)}
function cameraSettings(n){openModal(`<button class="close" onclick="closeModal()">×</button><h2>Camera settings</h2><p>${n}</p><div class="form"><label>Resolution<select><option>1080p</option><option>720p</option></select></label><label>Frame rate<select><option>30 FPS</option><option>24 FPS</option></select></label></div><div class="modal-actions"><button class="btn primary" onclick="closeModal();toast('Camera settings saved')">Save changes</button></div>`)}
function scanCameras(){toast("Camera scan complete","48 of 48 cameras are online.")}
function generateReport(n){toast("Report generated",`${n} is ready for download.`);exportCSV()}
function exportCSV(){const rows=[["Junction","ID","Flow","Speed","Queue","Status"],...state.junctions];const blob=new Blob([rows.map(r=>r.join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="flowsight-report.csv";a.click();URL.revokeObjectURL(a.href);toast("CSV downloaded","Traffic report exported successfully.")}
function openModal(x){modal.innerHTML=x;modalBg.classList.add("show")}function closeModal(){modalBg.classList.remove("show")}modalBg.onclick=e=>{if(e.target===modalBg)closeModal()}
function toggleSidebar(){document.getElementById("sidebar").classList.toggle("closed");document.querySelector(".main").style.marginLeft=document.getElementById("sidebar").classList.contains("closed")?"78px":""}
function mobileSidebar(){document.getElementById("sidebar").classList.toggle("mobile")}
function toggleTheme(){document.body.classList.toggle("dark");toast("Theme changed",document.body.classList.contains("dark")?"Dark mode enabled":"Light mode enabled")}
function showNotifications(){openModal(`<button class="close" onclick="closeModal()">×</button><h2>Notifications</h2><p>3 alerts require your attention.</p><div class="list"><div class="list-row"><div class="list-icon">!</div><div><strong>High severity incident</strong><p>Market Circle · 8 minutes ago</p></div></div><div class="list-row"><div class="list-icon">▣</div><div><strong>Camera recovered</strong><p>North Gate · 12 minutes ago</p></div></div><div class="list-row"><div class="list-icon">↗</div><div><strong>Traffic improved</strong><p>Central Square · 18 minutes ago</p></div></div></div>`)}
function changeDate(){toast("Date filter","Showing live data for October 6, 2026.")}
function openProfile(){openModal(`<button class="close" onclick="closeModal()">×</button><h2>Operator profile</h2><p>FlowSight Network Operations</p><div class="card metric" style="margin-top:14px"><span>Signed in as</span><strong>Hanuma</strong><span>Network Operator</span></div><div class="modal-actions"><button class="btn primary" onclick="closeModal()">Close</button></div>`)}
setPage("overview");
